#!/usr/bin/env bash
# Цифровая интенсивность (digital vibrance), как в панели NVIDIA на Windows.
#
#   vibrance.sh set <0..100>   — выставить и применить
#   vibrance.sh get            — текущее значение
#   vibrance.sh restore        — применить сохранённое (для автозапуска)
#
# На Wayland ручки из nvidia-settings нет: та работала через XRandR и на
# сеансе Wayland не действует вовсе. Зато цветом всего экрана распоряжается
# сам компоновщик — Hyprland умеет прогонять кадр через свой шейдер, и
# насыщенность считается там же, где картинка собирается. Способ не зависит
# от видеокарты: одинаково работает на NVIDIA, AMD и Intel.
#
# Шкала намеренно повторяет привычную: 50 — как есть, 100 — максимум,
# ниже 50 — приглушение до чёрно-белого на нуле.
set -u

CONF="${XDG_CONFIG_HOME:-$HOME/.config}"
SHADER_DIR="$CONF/hypr/shaders"
SHADER="$SHADER_DIR/vibrance.frag"
STATE="$CONF/panacea/.vibrance"

cur() { [ -f "$STATE" ] && cat "$STATE" || echo 50; }

# Сказать Hyprland, какой шейдер брать.
#
# Через hyprctl eval, а не keyword: новый (не-legacy, он же Lua) парсер
# конфига keyword молча отвергает — и выходит при этом с нулевым кодом, так
# что ошибку не видно, а настройка никуда не уезжает. Ровно то же самое уже
# случилось с настройками мониторов. keyword оставляем запасным путём для
# старых конфигов.
set_shader() {
    local val="$1" out
    out="$(hyprctl eval "hl.config({ decoration = { screen_shader = \"$val\" } })" 2>&1)"
    case "$out" in
        ok*) return 0 ;;
        *)   hyprctl keyword decoration:screen_shader "$val" >/dev/null 2>&1 ;;
    esac
}


# Какой диалект GLSL просит компоновщик — не догадка, а то, что зашито в нём
# самом. Hyprland линкует наш фрагментный шейдер со своим вершинным, и версии
# обязаны совпадать: на «#version 300 es» внутри Hyprland шейдер без строки
# версии считается 1.00, и драйвер NVIDIA отвечает «all shaders must use same
# shading language version», рисуя поверх экрана красную рамку. Mesa то же
# несовпадение прощает молча — поэтому проверить это на одной машине нельзя.
#
# Спрашиваем у бинарника: grep -a читает его как текст, binutils не нужен.
dialect() {
    local bin ver
    bin=$(command -v Hyprland 2>/dev/null) || { echo es3; return; }
    ver=$(grep -ao '#version [0-9]\+ es' "$bin" 2>/dev/null | head -1 | tr -dc '0-9')
    [ -n "$ver" ] && [ "$ver" -ge 300 ] && echo es3 || echo es1
}

# Только ASCII: компилятор NVIDIA спотыкается на не-ASCII байтах даже внутри
# комментариев и отвечает «error C3001: no program defined», то есть будто
# исходника нет вовсе. Поэтому пояснения по-русски остаются здесь, а в .frag
# уходит английский.
#
# lum  — яркость по Rec.709, серый той же светлоты, что и цвет: от него
#        отталкиваемся, чтобы подъём насыщенности не гнал в пересвет.
# sat  — насколько цвет насыщен сейчас. В этом и отличие «вибранса» от
#        простой насыщенности: уже яркие цвета трогаем слабо, блёклые —
#        сильно, иначе лица и небо первыми уезжают в кислоту.
#
# Пишем во временный файл и переименовываем. Компоновщик перечитывает шейдер,
# как только ему называют путь, а ползунок зовёт нас на каждое движение — и
# Hyprland успевал открыть файл на середине записи. Переименование в пределах
# файловой системы атомарно: он видит либо старый файл целиком, либо новый.
write_shader() {   # $1 — сила, $2 — es3 | es1
    local strength="$1" want="$2" tmp="$SHADER.new"
    local head body_out sample

    if [ "$want" = "es3" ]; then
        head="#version 300 es
precision highp float;
in vec2 v_texcoord;
uniform sampler2D tex;
out vec4 fragColor;"
        sample="texture(tex, v_texcoord)"
        body_out="fragColor"
    else
        head="precision highp float;
varying vec2 v_texcoord;
uniform sampler2D tex;"
        sample="texture2D(tex, v_texcoord)"
        body_out="gl_FragColor"
    fi

    cat > "$tmp" <<EOF
// Generated by panacea/scripts/vibrance.sh -- edits will be overwritten.
$head

const float STRENGTH = ${strength};

void main() {
    vec4 px = $sample;

    float lum = dot(px.rgb, vec3(0.2126, 0.7152, 0.0722));

    float mx  = max(px.r, max(px.g, px.b));
    float mn  = min(px.r, min(px.g, px.b));
    float sat = mx - mn;

    float weight = STRENGTH > 0.0 ? (1.0 - sat) : 1.0;
    float amount = STRENGTH * weight;
    vec3 outRgb = mix(vec3(lum), px.rgb, 1.0 + amount);

    $body_out = vec4(clamp(outRgb, 0.0, 1.0), px.a);
}
EOF
    mv -f "$tmp" "$SHADER"
}

apply() {
    local pct="$1"

    # 50 — нейтраль: шейдер снимаем совсем, чтобы кадр шёл мимо лишнего
    # прохода. Так «выключено» действительно ничего не стоит.
    if [ "$pct" -eq 50 ]; then
        set_shader '[[EMPTY]]'
        return
    fi

    # 50→0.0, 100→1.0, 0→-1.0
    local strength
    strength="$(awk -v p="$pct" 'BEGIN { printf "%.4f", (p - 50) / 50 }')"

    mkdir -p "$SHADER_DIR"
    write_shader "$strength" "$(dialect)"
    set_shader "$SHADER"

}


case "${1:-}" in
    set)
        pct="${2:-50}"
        [ "$pct" -lt 0 ]   && pct=0
        [ "$pct" -gt 100 ] && pct=100
        mkdir -p "$(dirname "$STATE")"
        echo "$pct" > "$STATE"
        apply "$pct"
        echo "$pct"
        ;;
    get)     cur ;;
    restore) apply "$(cur)" ;;
    *)       echo "usage: vibrance.sh set <0..100>|get|restore" >&2; exit 1 ;;
esac
